language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
node_js:
  - "6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip ffmpeg
install:
  - ./install.sh
  - nodejs ./node_modules/gulp/bin/gulp.js --production
before_script:
  - cat .env

cache:
  pip: true
  directories:
  - vendor
  - node_modules
