language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
install:
  - sudo apt-get install python2.7 python-pip ffmpeg nodejs
  - ./install.sh
  - nodejs ./node_modules/gulp/bin/gulp.js --production
