language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
install:
  - sudo apt-get install --upgrade python-pip ffmpeg npm node nodejs openssl
  - ./install.sh
  - nodejs ./node_modules/gulp/bin/gulp.js --production
