language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip ffmpeg nodejs
install:
  - ./install.sh
  - nvm run node ./node_modules/gulp/bin/gulp.js --production
before_script:
  - cat .env

cache:
  pip: true
  directories:
  - vendor
  - node_modules
