language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
install:
  - sudo apt-get purge node nodejs npm
  - sudo apt-get install python-pip ffmpeg nodejs python-openssl
  - ./install.sh
  - node ./node_modules/gulp/bin/gulp.js --production
cache:
  pip: true
  directories:
  - vendor
  - node_modules
