sudo: false
language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
matrix:
  allow_failures:
  - php: '5.6'
  - php: hhvm

services:
  - postgresql

addons:
  apt:
    packages:
    - python-pip
    - ffmpeg

before_install:
  - nvm install 6
  - psql -c 'create database travis_ci_test;' -U postgres
  - openssl aes-256-cbc -K $encrypted_5f496bf5950e_key -iv $encrypted_5f496bf5950e_iv -in .env.travis.enc -out .env -d
install:
  - composer create-project
  - npm install
  - pip install --user cfscrape
  - pip install --user selenium
  - php artisan migrate --seed
  - node ./node_modules/gulp/bin/gulp.js --production
before_script:
  - php -v
  - npm -v
  - node -v
  - python -V
after_script:
  - python ./app/AnimeSentinel/Python/CloudFlare.py "http://kissanime.to/"

cache:
  pip: true
  directories:
  - vendor
  - node_modules
