language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
install:
  - apt-get install python python-pip
  - composer install
  - sudo npm install
  - nodejs ./node_modules/gulp/bin/gulp.js --production
